manoalist/manoalist

app/imports/ui/components/User.jsx

Further work will be done w/ the implementation of the profile page

Make skeleton of user component

---

app/imports/api/user/User.js

Very basic user api implemented.

Implement User Api

---

app/imports/ui/components/Footer.jsx

Changes to be committed:
modified:   app/imports/ui/components/Footer.jsx
Completed the change to make the register button only present when the user is not logged in.  Put a welcome message in it's place for now.  We could easily replace this with contact us link in the future."

 On branch issue-044

---

app/imports/ui/pages/Signup.jsx

Changes to be committed:
modified:   app/imports/ui/pages/Signup.jsx
Completed implementing a sweet alert to ensure the user agrees to the terms of use during registration.

 On branch issue-054

---

app/imports/ui/pages/Signup.jsx

1. check email end with @hawaii.edu
2. check the password is at least 8 characters long(we can change to use regExp easily)
3. fix a bug that if directly click the signup button, it will still pop a message that "Your account has been created."

issue#48 Create a filter to check the user registration to have @hawaii.edu email 

---

app/imports/api/item/Item.js
app/imports/ui/components/ItemItem.jsx
app/imports/ui/pages/ListItem.jsx
config/settings.development.json

Clicking the button updates the 'flagged' field for the item to true
add reportReanson to items. Users can provide report reason and admin should see this on their admin page.
Make the additional change to listItem: now users are able to see the flagged items
(to prevent malicious report for example if a user reported all the items, then our list will be empty )

Issue 052 implement report button to Item

---

app/imports/ui/components/Footer.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/Contact.jsx

modified the footer, and create another page for contact (Customer service).

modified the footer

---

app/imports/ui/pages/Signin.jsx

issue-059 edit Signin page now admin is default direct to HomeAdmin page to="\admin"

set admins default to the admin page

---

app/imports/ui/components/NavBar.jsx

On the navbar:
Change the logo to just the text without the circle.
Should be good to merge, just wanted to make a pull request just in case lol

On branch issue-068

---

app/imports/ui/components/AdminApproveItem.jsx

implement the functionality of delete and approve button

Issue 062 Setup the functionality to approve or deny a posted item on the admin page #62

---

app/imports/ui/components/AdminApproveItem.jsx
app/imports/ui/components/AdminBan.jsx
app/imports/ui/pages/HomeAdmin.jsx

add restore button: change isFalgged to false.
add delete button functionality: remove the item from the list.
add ban user button functionality: change user isBanned to true.  and remove item from the list.
add segment to show report reason

Issue 061 create functionality for AdminBan

---

app/imports/ui/components/ItemItem.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/AddCategory.jsx
app/imports/ui/pages/HomeAdmin.jsx

1. App.jsx add link to addCategory page '/addCate'
2. HomeAdmin link button to addCategory page
3. AddCategory page
-  admin can create a new category (cannot add an existing category)
-  admin can see all the category on this page
-  admin can delete a category that has no item under it. (cannot delete category has item inside)
4. ItemItem.jsx 
- solved error in listItem page ( <a> cannot appear as a descendant of <a>)
- fix UI issue that cards were stacked together

Issue 083 add category

---

app/imports/ui/pages/ListItem.jsx

ListItem page add Pagination to show 20 items each page

add Pagination

---

app/imports/api/mail/Contactus.js
app/imports/ui/pages/Contact.jsx
config/settings.development.json

I change the database for it, it has these properties: Name, Subject, Type, Content, Email. Personally, I'd like to make the Contact Us as a public functionality.
Note: For submission, the field of Name can be empty, and its default value will be "customer" that for in case users don't want to put their name on it.

Contact us functionality

---

app/imports/ui/pages/ListItem.jsx

the title will be
All Items/CategoryGroup/CategoryName

Update list items title to be the category group and name

---

app/imports/api/item/Item.js
app/imports/api/user/User.js
app/imports/ui/components/ItemItem.jsx
app/imports/ui/pages/AddItem.jsx
app/imports/ui/pages/ItemPage.jsx

1. add numberOfLike in Item, to count number of like
2. add liked in User, array to store items id user liked.
3. implement like button in ItemItem
4. implement like button in Item Page

Implement like functionality for items

---

app/imports/ui/pages/AddCategory.jsx

AddCategory.jsx
1. move delete to top
2. add error catch to delete

move delete to top

---

app/imports/ui/layouts/App.jsx
app/imports/ui/pages/EditItem.jsx

go to brach issue-153 and see UI here
http://localhost:3000/#/editItem/24kGqz4DL2tjtW2bB/School

Issue 153 create edit page

---

app/imports/ui/pages/Home.jsx

use likes to find popular items

---

app/imports/api/mail/Contactus.js
app/imports/ui/components/EmailItem.jsx
app/imports/ui/pages/Contact.jsx
app/imports/ui/pages/HomeAdmin.jsx
app/imports/ui/pages/ItemPage.jsx

1. Implement inbox in the admin page
2. create emailItem component
3. edit beRead to Contactus api and update Contact.jsx
4. fix ESlint error of Item page

Issue 155 Implement inbox in admin page

---

app/imports/startup/server/Accounts.js
app/imports/ui/components/NavBar.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/ChangePsword.jsx

users are able to reset their password after they login. The confirm must match the new password user set up, and the new password cannot be same as the current one.

Issue-157-the functionality of Change password

---

app/imports/ui/components/AdminBan.jsx
app/imports/ui/pages/Signin.jsx

If the users has been ban by Admin, they cannot login to our web. They will be kicked out and get a reminder of contacting Admin.

add the result of Ban user

---

app/imports/api/mail/Contactus.js
app/imports/startup/server/Publications.js
app/imports/ui/components/EmailItem.jsx
app/imports/ui/components/NavBar.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/Inbox.jsx

User can receive notification from Admin
User can reply email
have red dot when have not read email

Issue 177 Implement inbox for all users in NavBar

---

app/imports/startup/server/Mongo.js
app/imports/ui/components/EmailItem.jsx
app/imports/ui/pages/Home.jsx
app/imports/ui/pages/HomeAdmin.jsx
app/imports/ui/pages/Inbox.jsx
app/imports/ui/pages/ItemPage.jsx

Please test it and give me some feedback about the email system

finish implement email functionality

---

app/imports/ui/components/NavBar.jsx
app/imports/ui/layouts/App.jsx
app/imports/ui/pages/Likes.jsx

created page to hold users likes
added dropdown item to navbar to access page

Issue 180 likes page
